# Generated by Django 4.1.13 on 2024-02-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COCHE', 'Coche'), ('CICLOMOTOR', 'Ciclomotor'), ('MOTOCICLETA', 'Motocicleta')], max_length=50)),
                ('chasis', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(choices=[('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('BLANCO', 'Blanco')], max_length=20)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_matriculacion', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('suspendido', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.marca')),
            ],
        ),
    ]
